services:
  - type: web
    name: sahu-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sahu-db
          property: connectionString
    healthCheckPath: /health
    plan: free
